### ISSUE TITLE
chain should return a Parser

### ISSUE THREAD

**Issue by IceSentry** [LowLevelJavaScript/Parser-Combinators-From-Scratch#4]
https://github.com/LowLevelJavaScript/Parser-Combinators-From-Scratch/blob/1e876fecdc8ddd840a0b1f3c81e7667e2a7f31b0/episode-7/index.js#L198-L201

The `.chain()` here should return `succeed([...res, tag('Options')(remaining)])`

**Comment by lowbyteproductions** [comment]
Good catch, thanks! Was meant to use `.map()` here - but chain with succeedWith would also work!
